"""
Django settings for chess_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*2tp-+=h6232w=#^^p!sags$sa1qf937#)n=&lj#d4i^ys2&7h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third party
    'allauth',                       # ← ADD THIS
    'allauth.account',               # ← ADD THIS
    'allauth.socialaccount',         # ← ADD THIS
    'allauth.socialaccount.providers.google',  # ← ADD THIS

    'accounts',
    'game'
]


# Required by django-allauth
# Tells allauth which site it's running on
SITE_ID = 1


# ─────────────────────────────────────────
# AUTHENTICATION BACKENDS
# ─────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    # Default Django backend (email + password login)
    'django.contrib.auth.backends.ModelBackend',

    # Allauth backend (Google OAuth login)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Use email as the primary identifier
ACCOUNT_LOGIN_METHODS = {'email'}

# Email is required for signup
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Don't force email verification during development
# Change to 'mandatory' in production
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Where to go after Google login
LOGIN_REDIRECT_URL = '/game/'

# Where to go after logout
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# Google OAuth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'chess_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chess_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


# ─────────────────────────────────────────
# PASSWORD VALIDATION RULES
# These run when a user sets a password
# ─────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        # Password can't be too similar to username or email
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Password must be at least 8 characters
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        # Password can't be "password", "12345678" etc.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Password can't be entirely numbers
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Where to find CSS/JS files during development
STATICFILES_DIRS = [BASE_DIR / 'static']

# Where collectstatic puts files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use our CustomUser instead of Django's built-in User
AUTH_USER_MODEL = 'accounts.CustomUser'


# Where to redirect after login/logout
LOGIN_REDIRECT_URL  = '/game/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Where to redirect unauthenticated users who try to visit a protected page
LOGIN_URL = '/accounts/login/'


# ─────────────────────────────────────────
# PASSWORD HASHING
# ─────────────────────────────────────────
# Django tries these hashers in ORDER.
# The FIRST one is used for new passwords.
# The others are kept so old passwords still work.

PASSWORD_HASHERS = [
    # BCrypt is now the default for all new passwords
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',

    # Fallback — existing PBKDF2 passwords still work
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# ─────────────────────────────────────────
# SESSION CONFIGURATION
# ─────────────────────────────────────────

# Store sessions in the database (most secure option)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session cookie name (what appears in the browser)
SESSION_COOKIE_NAME = 'chess_sessionid'

# Session expires when browser closes (set to True for extra security)
# False = session persists even after closing browser (like "remember me")
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# How long the session lasts in seconds
# 1209600 = 2 weeks
SESSION_COOKIE_AGE = 1209600

# Prevent JavaScript from reading the session cookie
# This protects against XSS attacks
SESSION_COOKIE_HTTPONLY = True

# Only send cookie over HTTPS (set True in production)
SESSION_COOKIE_SECURE = False  # Change to True in production

# Prevent cross-site request forgery
CSRF_COOKIE_HTTPONLY = False   # Must be False so JS can read CSRF token


# ─────────────────────────────────────────
# EMAIL CONFIGURATION
# ─────────────────────────────────────────

# During development: prints emails to the terminal instead of sending them
# This means you can see the reset link without needing a real email account
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ── For production, replace the above with SMTP settings: ──
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# Who the reset email appears to come from
DEFAULT_FROM_EMAIL = 'Chess Game <noreply@chessgame.com>'